In [17]:
L = 100.0  # length of the console
number_of_elements = 2  # number of elements in the discretization

In [18]:
from sigmaepsilon.mesh import PolyData1d as LineMesh, PointData
from sigmaepsilon.math.linalg import linspace
from sigmaepsilon.mesh.space import StandardFrame, PointCloud
from sigmaepsilon.mesh.utils.space import frames_of_lines
from sigmaepsilon.mesh.cells import L2 as CellData
import numpy as np

# space
GlobalFrame = StandardFrame(dim=3)

# mesh
p0 = np.array([0.0, 0.0, 0.0])
p1 = np.array([L, 0.0, 0.0])
coords = linspace(p0, p1, number_of_elements + 1)
coords = PointCloud(coords, frame=GlobalFrame).show()
topo = np.zeros((number_of_elements, 2), dtype=int)
topo[:, 0] = np.arange(number_of_elements)
topo[:, 1] = np.arange(number_of_elements) + 1

# pointdata
pd = PointData(coords=coords, frame=GlobalFrame)

# celldata
frames = frames_of_lines(coords, topo)
cd = CellData(topo=topo, frames=frames)

# set up mesh and structure
mesh = LineMesh(pd, cd, frame=GlobalFrame)

In [19]:
rng = [0, 1]
points = np.linspace(rng[0], rng[1], 3)
#x_approx = mesh.cells_coords(points=points, rng=rng)
x_approx = cd.coords(points=points, rng=rng)


In [20]:
points

array([0. , 0.5, 1. ])

In [21]:
x_approx[:, :, 0].flatten()

array([  0.,  25.,  50.,  50.,  75., 100.])

In [22]:
coords[:, 0]

Array([  0.,  50., 100.])

In [23]:
assert np.allclose(points, np.array([0. , 0.5, 1. ]))
assert np.allclose(x_approx[:, :, 0].flatten(), np.array([  0.,  25.,  50.,  50.,  75., 100.]))
assert np.allclose(coords[:, 0], np.array([  0.,  50., 100.]))